/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
select
  country,
  count(distinct customer_key) as total_customers
from gold.gold_dim_customers
group by country
order by total_customers desc

-- Find total customers by gender
select
  gender,
  count(distinct customer_key) as total_customers
from gold.gold_dim_customers
group by gender
order by total_customers desc

-- Find total products by category
select
  category,
  count(distinct product_key) as total_products
from gold.gold_dim_products
group by category
order by total_products desc

-- What is the average cost in each category?
select
  category,
  round(avg(cost), 2) as avg_cost
from gold.gold_dim_products
group by category
order by avg_cost desc
  
-- What is the total revenue generated for each category?
select
  p.category,
  sum(f.sales_amount) as total_revenue
from gold.gold_fact_sales f
left join gold.gold_dim_products p
on f.product_key = p.product_key
group by p.category
order by total_revenue desc

-- What is the total revenue generated by each customer?
select
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) as total_revenue
from gold.gold_fact_sales f
left join gold.gold_dim_customers c
	on c.customer_key = f.customer_key
group by
	c.customer_key,
	c.first_name,
	c.last_name
order by total_revenue desc

-- What is the distribution of sold items across countries?
select
	c.country,
	sum(f.quantity) as total_sold_items
from gold.gold_fact_sales f
left join gold.gold_dim_customers c
	on f.customer_key = c.customer_key
group by c.country
order by total_sold_items desc
